
[tasks.install-app]
description = "Install dependencies and build the project"
run = "go build -o ~/go/bin/kube-tunnel ./cmd"

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tools]
go = "1.25.0"
golangci-lint = "2.4.0"
pre-commit = "4.3.0"
