name: Feature Request
description: Suggest an idea or enhancement for kube-tunnel
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - snakeice

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

        Please provide as much detail as possible to help us understand your use case and requirements.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A brief, descriptive title for the feature
      placeholder: "Add support for WebSocket proxying"
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - Performance improvement
        - New protocol support
        - Configuration option
        - API enhancement
        - Monitoring/Observability
        - Security enhancement
        - Documentation improvement
        - Developer experience
        - Platform support
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        Describe the problem you're trying to solve or the limitation you've encountered.

        For example:
        - "Currently, I need to manually manage port-forwards for multiple services..."
        - "When working with high-traffic services, I need better connection pooling..."
        - "For debugging purposes, I need more detailed metrics about..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen? Describe your ideal solution.
      placeholder: |
        Describe your proposed solution in detail:

        - What should the feature do?
        - How should it work?
        - What should the API/interface look like?
        - Any configuration options needed?

        Feel free to include examples or mockups!
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: |
        Describe alternative solutions you've thought about:

        - Other tools or approaches you've tried
        - Workarounds you're currently using
        - Why those alternatives don't fully solve the problem

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my workflow"
        - "High - Significantly improves my use case"
        - "Critical - Blocking my adoption/usage"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low - Simple configuration or minor enhancement"
        - "Medium - New functionality but uses existing patterns"
        - "High - Significant new functionality or architectural changes"
        - "Unknown - Not sure about implementation complexity"

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Provide concrete examples of how this feature would be used:

        1. Development workflow: "When developing microservices locally..."
        2. Testing scenario: "When running integration tests..."
        3. Production use case: "For monitoring high-traffic services..."
        4. Troubleshooting: "When debugging connection issues..."

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How would you measure the success of this feature?
      placeholder: |
        Define what "done" looks like:

        - Specific functionality that must work
        - Performance requirements (if applicable)
        - Compatibility requirements
        - Documentation requirements
        - Testing requirements

  - type: checkboxes
    id: feature-scope
    attributes:
      label: Feature Scope
      description: Which areas would this feature affect?
      options:
        - label: Core proxy functionality
        - label: Health monitoring system
        - label: DNS/mDNS configuration
        - label: Performance and caching
        - label: Configuration and CLI
        - label: Docker/Kubernetes deployment
        - label: Logging and debugging
        - label: Documentation
        - label: Testing and CI/CD
        - label: Security

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical details or constraints to consider?
      placeholder: |
        If you have technical insights, please share:

        - Specific technologies or libraries that might help
        - Potential challenges or constraints
        - Compatibility considerations
        - Performance implications
        - Security considerations

  - type: textarea
    id: examples
    attributes:
      label: Examples and Mockups
      description: Provide examples, code snippets, or mockups if helpful
      render: shell
      placeholder: |
        # Example command usage:
        ./kube-tunnel --new-feature-flag=value

        # Example configuration:
        export NEW_FEATURE_ENABLED=true

        # Example API response:
        curl http://localhost:80/new-endpoint

        # Or describe the interface you envision

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - "No breaking changes expected"
        - "Minor breaking changes (easily migratable)"
        - "Major breaking changes required"
        - "Unsure about breaking changes"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to work on implementing this feature
        - label: I can help with testing the implementation
        - label: I can help with documentation
        - label: I can provide feedback during development
        - label: I can help with code review

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        Add any other context, links, or information:

        - Links to related projects or documentation
        - Screenshots or diagrams
        - Research you've done
        - Community feedback you've received
        - Timeline considerations

  - type: checkboxes
    id: research
    attributes:
      label: Research Done
      description: What research have you done for this feature?
      options:
        - label: Searched existing issues and discussions
        - label: Reviewed the documentation
        - label: Looked at similar projects or tools
        - label: Discussed with other users or team members
        - label: Tested with current workarounds
        - label: Considered implementation approaches

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
